Formatting aangepast, cookieeval toegevoegd aan digirooster en algemene verbeteringen

diff --git a/.local/bin/archivedl b/.local/bin/archivedl
--- a/.local/bin/archivedl
+++ b/.local/bin/archivedl
@@ -3,7 +3,7 @@
 #
 # Usage: archivedl https://archive.org/download/<something> <location>
 
-[ -z "$1" ] && echo "missing url operand" && exit 1
+[ -z "$1" ] && echo 'missing url operand' && exit 1
 [ -z "$2" ] && echo "missing destination file operand after '$1'" && exit 1
 
 wget --spider "$1" || exit 1
@@ -12,7 +12,7 @@ urlcode=$(echo "$1" | sed "s/.*\///")
 tmploc="$2/$urlcode"
 
 if [ ! -f "$tmploc" ]; then
-	curl "$1" | grep -o "href=\"[^\"]*" | awk 'NR == 1, $0 ~ /\/details\/'"$urlcode"'/ { next } /\/$/ || /'"$urlcode"'/ || /__ia_thumb.jpg/ { next } { sub(/href="/, "") ; print }' > "$tmploc"
+	curl "$1" | grep -o 'href="[^"]*' | awk 'NR == 1, $0 ~ /\/details\/'"$urlcode"'/ { next } /\/$/ || /'"$urlcode"'/ || /__ia_thumb.jpg/ { next } { sub(/href="/, "") ; print }' > "$tmploc"
 	$EDITOR "$tmploc"
 fi
 
